// Comprehensive list of world country calling codes with national phone number length rules
export const COUNTRY_CODES = [
  { code: "+91", country: "India", flag: "🇮🇳", iso: "IN", minLength: 10, maxLength: 10 },
  { code: "+1", country: "United States", flag: "🇺🇸", iso: "US", minLength: 10, maxLength: 10 },
  { code: "+1", country: "Canada", flag: "🇨🇦", iso: "CA", minLength: 10, maxLength: 10 },
  { code: "+44", country: "United Kingdom", flag: "🇬🇧", iso: "GB", minLength: 10, maxLength: 11 },
  { code: "+61", country: "Australia", flag: "🇦🇺", iso: "AU", minLength: 9, maxLength: 9 },
  { code: "+971", country: "United Arab Emirates", flag: "🇦🇪", iso: "AE", minLength: 9, maxLength: 9 },
  { code: "+65", country: "Singapore", flag: "🇸🇬", iso: "SG", minLength: 8, maxLength: 8 },
  { code: "+49", country: "Germany", flag: "🇩🇪", iso: "DE", minLength: 10, maxLength: 11 },
  { code: "+33", country: "France", flag: "🇫🇷", iso: "FR", minLength: 9, maxLength: 9 },
  { code: "+81", country: "Japan", flag: "🇯🇵", iso: "JP", minLength: 10, maxLength: 10 },
  { code: "+86", country: "China", flag: "🇨🇳", iso: "CN", minLength: 11, maxLength: 11 },
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦", iso: "SA", minLength: 9, maxLength: 9 },
  { code: "+974", country: "Qatar", flag: "🇶🇦", iso: "QA", minLength: 8, maxLength: 8 },
  { code: "+965", country: "Kuwait", flag: "🇰🇼", iso: "KW", minLength: 8, maxLength: 8 },
  { code: "+968", country: "Oman", flag: "🇴🇲", iso: "OM", minLength: 8, maxLength: 8 },
  { code: "+973", country: "Bahrain", flag: "🇧🇭", iso: "BH", minLength: 8, maxLength: 8 },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩", iso: "BD", minLength: 10, maxLength: 10 },
  { code: "+92", country: "Pakistan", flag: "🇵🇰", iso: "PK", minLength: 10, maxLength: 10 },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰", iso: "LK", minLength: 9, maxLength: 9 },
  { code: "+977", country: "Nepal", flag: "🇳🇵", iso: "NP", minLength: 10, maxLength: 10 },
  { code: "+975", country: "Bhutan", flag: "🇧🇹", iso: "BT", minLength: 8, maxLength: 8 },
  { code: "+960", country: "Maldives", flag: "🇲🇻", iso: "MV", minLength: 7, maxLength: 7 },
  { code: "+60", country: "Malaysia", flag: "🇲🇾", iso: "MY", minLength: 9, maxLength: 10 },
  { code: "+62", country: "Indonesia", flag: "🇮🇩", iso: "ID", minLength: 9, maxLength: 12 },
  { code: "+63", country: "Philippines", flag: "🇵🇭", iso: "PH", minLength: 10, maxLength: 10 },
  { code: "+66", country: "Thailand", flag: "🇹🇭", iso: "TH", minLength: 9, maxLength: 9 },
  { code: "+84", country: "Vietnam", flag: "🇻🇳", iso: "VN", minLength: 9, maxLength: 10 },
  { code: "+82", country: "South Korea", flag: "🇰🇷", iso: "KR", minLength: 9, maxLength: 10 },
  { code: "+852", country: "Hong Kong", flag: "🇭🇰", iso: "HK", minLength: 8, maxLength: 8 },
  { code: "+886", country: "Taiwan", flag: "🇹🇼", iso: "TW", minLength: 9, maxLength: 9 },
  { code: "+39", country: "Italy", flag: "🇮🇹", iso: "IT", minLength: 9, maxLength: 10 },
  { code: "+34", country: "Spain", flag: "🇪🇸", iso: "ES", minLength: 9, maxLength: 9 },
  { code: "+31", country: "Netherlands", flag: "🇳🇱", iso: "NL", minLength: 9, maxLength: 9 },
  { code: "+41", country: "Switzerland", flag: "🇨🇭", iso: "CH", minLength: 9, maxLength: 9 },
  { code: "+46", country: "Sweden", flag: "🇸🇪", iso: "SE", minLength: 9, maxLength: 10 },
  { code: "+47", country: "Norway", flag: "🇳🇴", iso: "NO", minLength: 8, maxLength: 8 },
  { code: "+45", country: "Denmark", flag: "🇩🇰", iso: "DK", minLength: 8, maxLength: 8 },
  { code: "+358", country: "Finland", flag: "🇫🇮", iso: "FI", minLength: 9, maxLength: 11 },
  { code: "+353", country: "Ireland", flag: "🇮🇪", iso: "IE", minLength: 9, maxLength: 9 },
  { code: "+32", country: "Belgium", flag: "🇧🇪", iso: "BE", minLength: 9, maxLength: 9 },
  { code: "+43", country: "Austria", flag: "🇦🇹", iso: "AT", minLength: 10, maxLength: 11 },
  { code: "+351", country: "Portugal", flag: "🇵🇹", iso: "PT", minLength: 9, maxLength: 9 },
  { code: "+30", country: "Greece", flag: "🇬🇷", iso: "GR", minLength: 10, maxLength: 10 },
  { code: "+48", country: "Poland", flag: "🇵🇱", iso: "PL", minLength: 9, maxLength: 9 },
  { code: "+420", country: "Czech Republic", flag: "🇨🇿", iso: "CZ", minLength: 9, maxLength: 9 },
  { code: "+36", country: "Hungary", flag: "🇭🇺", iso: "HU", minLength: 9, maxLength: 9 },
  { code: "+40", country: "Romania", flag: "🇷🇴", iso: "RO", minLength: 9, maxLength: 10 },
  { code: "+7", country: "Russia", flag: "🇷🇺", iso: "RU", minLength: 10, maxLength: 10 },
  { code: "+7", country: "Kazakhstan", flag: "🇰🇿", iso: "KZ", minLength: 10, maxLength: 10 },
  { code: "+90", country: "Turkey", flag: "🇹🇷", iso: "TR", minLength: 10, maxLength: 10 },
  { code: "+972", country: "Israel", flag: "🇮🇱", iso: "IL", minLength: 9, maxLength: 9 },
  { code: "+20", country: "Egypt", flag: "🇪🇬", iso: "EG", minLength: 10, maxLength: 10 },
  { code: "+27", country: "South Africa", flag: "🇿🇦", iso: "ZA", minLength: 9, maxLength: 9 },
  { code: "+234", country: "Nigeria", flag: "🇳🇬", iso: "NG", minLength: 10, maxLength: 10 },
  { code: "+254", country: "Kenya", flag: "🇰🇪", iso: "KE", minLength: 9, maxLength: 9 },
  { code: "+233", country: "Ghana", flag: "🇬🇭", iso: "GH", minLength: 9, maxLength: 9 },
  { code: "+55", country: "Brazil", flag: "🇧🇷", iso: "BR", minLength: 10, maxLength: 11 },
  { code: "+52", country: "Mexico", flag: "🇲🇽", iso: "MX", minLength: 10, maxLength: 10 },
  { code: "+54", country: "Argentina", flag: "🇦🇷", iso: "AR", minLength: 10, maxLength: 10 },
  { code: "+56", country: "Chile", flag: "🇨🇱", iso: "CL", minLength: 9, maxLength: 9 },
  { code: "+57", country: "Colombia", flag: "🇨🇴", iso: "CO", minLength: 10, maxLength: 10 },
  { code: "+51", country: "Peru", flag: "🇵🇪", iso: "PE", minLength: 9, maxLength: 9 },
  { code: "+64", country: "New Zealand", flag: "🇳🇿", iso: "NZ", minLength: 8, maxLength: 10 },
];
