from datetime import datetime, timezone

def make_call_log(
    call_uuid=None,
    customer_name='',
    phone_number='',
    direction='outbound',
    duration=None,
    call_status='initiated',
    campaign_id=None,
    call_outcome=None,
    blocker=None,
    travel_dates=None,
    nights=None,
    guests=None,
    budget_stated=None,
    callback_datetime=None,
    competitor_named=None,
    verbatim_reason=None,
    human_followup_needed=None,
    summary=None,
    transcription=None,
    recording_url=None,
    raw_event_payload=None,
    timestamp=None,
):
    now = datetime.now(timezone.utc).isoformat()
    return {
        "call_uuid": call_uuid,
        "customer_name": customer_name or "",
        "phone_number": phone_number or "",
        "direction": direction or "outbound",
        "duration": str(duration) if duration is not None else "0",
        "call_status": call_status or "initiated",
        "campaign_id": campaign_id,
        "call_outcome": call_outcome,
        "blocker": blocker,
        "travel_dates": travel_dates,
        "nights": nights,
        "guests": guests,
        "budget_stated": budget_stated,
        "callback_datetime": callback_datetime,
        "competitor_named": competitor_named,
        "verbatim_reason": verbatim_reason,
        "human_followup_needed": human_followup_needed,
        "summary": summary or "",
        "transcription": transcription if transcription is not None else "",
        "recording_url": recording_url or "",
        "raw_event_payload": raw_event_payload,
        "timestamp": timestamp or now,
        "created_at": now,
        "updated_at": now,
    }
